const jobPosts = [
  {
    id: 1,
    title: "Research Assistant in Machine Learning",
    content: "Looking for a research assistant to support a machine learning project on image recognition. Ideal candidates should have experience with Python and TensorFlow.",
    author: "Dr. Sarah Thompson",
    date: "2023-11-01",
    tags: ["Machine Learning", "AI", "Python"],
  },
  {
    id: 2,
    title: "Field Assistant for Environmental Science Study",
    content: "Seeking a field research assistant to help collect and analyze data on local ecosystems. Must be comfortable with fieldwork and have experience with GIS tools.",
    author: "Dr. Emily Chen",
    date: "2023-11-03",
    tags: ["Environmental Science", "Fieldwork", "GIS"],
  },
  {
    id: 3,
    title: "Data Analyst for Social Science Research",
    content: "A research project on social media behavior requires a data analyst proficient in R and data visualization. The assistant will work with a small team to interpret large datasets.",
    author: "Prof. David Lee",
    date: "2023-11-05",
    tags: ["Social Science", "Data Analysis", "R"],
  },
  {
    id: 4,
    title: "Biology Lab Assistant for Microbiology Study",
    content: "We are looking for a lab assistant to support microbiology experiments. Responsibilities include preparing samples, recording data, and assisting in analysis.",
    author: "Dr. Amanda Green",
    date: "2023-11-07",
    tags: ["Biology", "Lab Work", "Microbiology"],
  },
  {
    id: 5,
    title: "Research Assistant in Renewable Energy",
    content: "Join our team to work on renewable energy solutions. We’re seeking someone with experience in energy systems and sustainable technologies.",
    author: "Prof. Michael Rogers",
    date: "2023-11-10",
    tags: ["Renewable Energy", "Sustainability", "Engineering"],
  },
  {
    id: 6,
    title: "Clinical Psychology Research Assistant",
    content: "A clinical psychology lab is looking for an assistant to help with participant interviews and data management. Background in psychology preferred.",
    author: "Dr. Rachel White",
    date: "2023-11-12",
    tags: ["Psychology", "Clinical Research", "Data Management"],
  },
  {
    id: 7,
    title: "Economics Research Assistant for Financial Analysis",
    content: "Looking for an assistant to support economic analysis on financial markets. Candidates with skills in Excel and econometrics are encouraged to apply.",
    author: "Dr. Thomas Gray",
    date: "2023-11-14",
    tags: ["Economics", "Finance", "Data Analysis"],
  },
];

export default jobPosts;
